const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      photo: 'https://i.postimg.cc/Y0LyTsMc/Livingston-Bed.jpg',
      oldPrice: 60,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: true,
      compare: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      photo: 'https://i.postimg.cc/pd8QbMnJ/Keziah-Platform-Bed.png',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      photo: 'https://i.postimg.cc/PJf1wLVS/Headboards.jpg',
      oldPrice: 50,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      photo:
        'https://i.postimg.cc/ZRRQxqQ5/Overstock-com-Online-Shopping-Bedding-Furniture-Electronics-Jewelry-Clothing-more.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      photo: 'https://i.postimg.cc/sXktfrnf/Chloe-Poliform-Bed-Milia-Shop.jpg',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      photo: 'https://i.postimg.cc/mgf0WBPm/Gerrald-Upholstered-Standard-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      photo: 'https://i.postimg.cc/RhWj401D/Ahumada-Upholstered-Standard-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      photo:
        'https://i.postimg.cc/xjszZ14S/Lexington-Tower-Place-Barrington-Upholstered-Platform-Bed.jpg',
      oldPrice: 60,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      photo:
        'https://i.postimg.cc/X7Hk98bd/Kelly-Wingback-Bed-Stripe-Beds-Bedroom-Furniture.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      photo:
        'https://i.postimg.cc/X7JwNCCJ/Emerald-Lizbeth-Velvet-Queen-Bed-Frame.jpg ',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      photo:
        'https://i.postimg.cc/6618018W/Chelsea-Modern-Bed-with-High-Feet-Berto-Salotti.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      photo: 'https://i.postimg.cc/fL1JwVn3/Andes-Deco-Upholstered-Storage-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      photo: 'https://i.postimg.cc/zfR7zR4W/Harper-Upholstered-Tall-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      photo: 'https://i.postimg.cc/Y0VBWFq7/Revley-Upholstered-Standard-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      photo:
        'https://i.postimg.cc/9Xv72nCx/Room-Board-Avery-Custom-Upholsterd-Storage-Bed-Modern-Custom-Beds-Platform-Beds.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      photo:
        'https://i.postimg.cc/0y12XgPs/BOLD-Double-bed-By-HC28-design-Frank-Chou.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      photo:
        'https://i.postimg.cc/kgWD7JfG/Porro-Spa-p-Makura-textile-bed-is-a-new-interpretation-of-domestic-warmth-that-is-a-cross-between.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      photo:
        'https://i.postimg.cc/m2tHWWv1/Raleigh-Curved-Upholstered-Tall-Footboard-Storage-Platform-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      photo:
        'https://i.postimg.cc/MGbcm6QN/Harper-Upholstered-Low-Storage-Platform-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      photo: 'https://i.postimg.cc/0jtDd8LP/Georgia-Velvet-Single-Bed-Blush.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      photo:
        'https://i.postimg.cc/q7MtQfx7/Tamsen-Curved-Upholstered-Footboard-Storage-Platform-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      photo: 'https://i.postimg.cc/XYWBGBZd/Raleigh-Wingback-Upholstered-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      photo: 'https://i.postimg.cc/gcwZfWFX/Clara-Platform-Bed.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      photo: 'https://i.postimg.cc/ZRQJr2VX/The-Best-Storage-Beds.jpg',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chair-1',
      name: 'Chair Bristique 24',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chair-2',
      name: 'Chair Ru Bristique 24',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chair-3',
      name: 'Chair Ru Bristique 24',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'Chair-4',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'sofa-1',
      name: 'Sofa Ru Bristique 24',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'sofa-2',
      name: 'Sofa Ru Bristique 24',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'sofa-3',
      name: 'Sofa Ru Bristique 24',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'sofa-4',
      name: 'Sofa Ru Bristique 24',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'table-1',
      name: 'Table Ru Bristique 24',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'table-2',
      name: 'Table Ru Bristique 24',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'table-3',
      name: 'Table Ru Bristique 24',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'table-4',
      name: 'Table Ru Bristique 24',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'dining-1',
      name: 'Dining Ru Bristique 24',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'dining-2',
      name: 'Dining Ru Bristique 24',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'dining-3',
      name: 'Dining Ru Bristique 24',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'dining-4',
      name: 'Dining Ru Bristique 24',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'dining-5',
      name: 'Dining Ru Bristique 24',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
  ],
  cart: {
    products: [],
  },
};

export default initialState;
